### ISSUE TITLE
Faield to configure web hooks on latest gitlab version

### ISSUE THREAD

**Issue by pavelpikta** [lean-delivery/ansible-role-gitlab#20]
##### SUMMARY

Faield to configure web hooks on latest gitlab version
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

[create_webhooks.yml](https://github.com/lean-delivery/ansible-role-gitlab/blob/master/tasks/create_webhooks.yml)
##### ANSIBLE VERSION

```
2.7.12
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-gitlab
  vars:
    gitlab_project_group_create: true
    gitlab_project_create: true
    gitlab_master_user_create: true
    gitlab_webhooks_create: true
    gitlab_labels_create: true
    gitlab_allow_local_requests: true
    gitlab_edition: ce
    gitlab_ssl_redirect_http_to_https: false
    gitlab_ldap_enabled: false
    gitlab_config_time_zone: UTC
    gitlab_email_enabled: false
    gitlab_mysql_enabled: false
    gitlab_smtp_enabled: false
    gitlab_admin_email: BF1U1swzaouACMj2S9aQ@admin.com
    gitlab_admin_name: superadmin
    gitlab_admin_username: superadmin1
    gitlab_admin_password: BF1U1swzaouACMj2S9aQ
    gitlab_admin_token: vsff3t4ferf34wfdsfRRrrfc234
```

##### EXPECTED RESULTS

Role complete successfully 
##### ACTUAL RESULTS

Role failed on task ```Add webhooks```

```
    failed: [test-aws-ubuntu1804-gitlab] (item={'value': {u'hook_url': u'http://server.example.com:8080/project/ci_main_branch_test', u'job_events': u'false', u'tag_push_events': u'false', u'issues_events': u'false', u'enable_ssl_verification': u'false', u'confidential_issues_events': u'false', u'note_events': u'false', u'push_events_branch_filter': u'', u'token': u'', u'push_events': u'true', u'merge_requests_events': u'false', u'pipeline_events': u'false', u'wiki_page_events': u'false'}, 'key': u'webhook1'}) => changed=false 
      cache_control: no-cache
      connection: close
      content: '{"error":"Invalid url given"}'
      content_length: '29'
      content_type: application/json
      date: Wed, 31 Jul 2019 11:15:53 GMT
      item:
        key: webhook1
        value:
          confidential_issues_events: 'false'
          enable_ssl_verification: 'false'
          hook_url: http://server.example.com:8080/project/ci_main_branch_test
          issues_events: 'false'
          job_events: 'false'
          merge_requests_events: 'false'
          note_events: 'false'
          pipeline_events: 'false'
          push_events: 'true'
          push_events_branch_filter: ''
          tag_push_events: 'false'
          token: ''
          wiki_page_events: 'false'
      json:
        error: Invalid url given
      msg: 'Status code was 422 and not [201]: HTTP Error 422: Unprocessable Entity'
      redirected: false
      server: nginx
      status: 422
      url: https://ip-172-31-181-123.ec2.internal/api/v4/projects/1/hooks
      vary: Origin
      x_request_id: S2LLgXCM0O5
      x_runtime: '0.058314'
    failed: [test-aws-centos7-gitlab] (item={'value': {u'hook_url': u'http://server.example.com:8080/project/ci_main_branch_test', u'job_events': u'false', u'tag_push_events': u'false', u'issues_events': u'false', u'enable_ssl_verification': u'false', u'confidential_issues_events': u'false', u'note_events': u'false', u'push_events_branch_filter': u'', u'token': u'', u'push_events': u'true', u'merge_requests_events': u'false', u'pipeline_events': u'false', u'wiki_page_events': u'false'}, 'key': u'webhook1'}) => changed=false 
      cache_control: no-cache
      connection: close
      content: '{"error":"Invalid url given"}'
      content_length: '29'
      content_type: application/json
      date: Wed, 31 Jul 2019 11:15:53 GMT
      item:
        key: webhook1
        value:
          confidential_issues_events: 'false'
          enable_ssl_verification: 'false'
          hook_url: http://server.example.com:8080/project/ci_main_branch_test
          issues_events: 'false'
          job_events: 'false'
          merge_requests_events: 'false'
          note_events: 'false'
          pipeline_events: 'false'
          push_events: 'true'
          push_events_branch_filter: ''
          tag_push_events: 'false'
          token: ''
          wiki_page_events: 'false'
      json:
        error: Invalid url given
      msg: 'Status code was 422 and not [201]: HTTP Error 422: Unprocessable Entity'
      redirected: false
      server: nginx
      status: 422
      url: https://ip-172-31-187-35.ec2.internal/api/v4/projects/1/hooks
      vary: Origin
      x_request_id: wJSUutTobB1
      x_runtime: '0.065077'
```
